Pilot 1844: Edit the semantic version tags after discussion
PilotDataPlatform/pipelinewatch pull request #11
Opened 2022-10-19 15:33 UTC by QXgu

## Summary

Edit the semantic version tags after discussion by moving get version out and edit the typo

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1844

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [ ] No

## Test Directions

(Additional instructions for how to run tests or validate functionality if not covered by unit tests)

2022-10-19 18:13 UTC, andricDu requested changes

2022-10-19 18:13 UTC, andricDu commented on .github/workflows/build-and-publish.yml
> +            type=raw,prefix=,suffix=,value=${{needs.get_version.outputs.app_version}}, enable=${{needs.extract-branch-name.outputs.branch=='main'}}
since we created a new job called `get-version` we will want to change `get_version` to `get-version` as it's no longer a local step.

2022-10-19 18:16 UTC, QXgu commented on .github/workflows/build-and-publish.yml
> +            type=raw,prefix=,suffix=,value=${{needs.get_version.outputs.app_version}}, enable=${{needs.extract-branch-name.outputs.branch=='main'}}
The get-version still have the id as get_verison, so I changed it here. Does we depend on job name or job id for this one?

2022-10-24 14:16 UTC, QXgu commented on .github/workflows/build-and-publish.yml
> +            type=raw,prefix=,suffix=,value=${{needs.get_version.outputs.app_version}}, enable=${{needs.extract-branch-name.outputs.branch=='main'}}
Fixed by changing them to get-version

2022-10-24 14:44 UTC, merged